---
# tasks file for ansible-role-mpop
- name: install system packages
  apt: name={{ item }} update_cache=yes
  with_items:
    - python-pip
    - git
    - python-dev
    - libjpeg-dev
    - zlib1g-dev
    - python-virtualenv

- name: update pip and virtualenv
  pip: name={{ item }} state=latest
  with_items:
    - virtualenv
    - pip

- name: Manually create virtualenv
  command: virtualenv {{ virtualenv_path }}

- name: Install package dependencies
  pip: name={{ item }} state=latest virtualenv={{ virtualenv_path }}
  with_items:
    - numpy
    - pykdtree


- name: Install mpop from git repo
  pip: name="git+https://github.com/pytroll/mpop.git@{{ mpop_branch }}#egg=mpop" virtualenv={{ virtualenv_path }}
